### ISSUE TITLE
Shadowrun 5th Edition (Advanced): Vehicles-Tab > Tests "Maneuver" > Roll a Driving Test (2 issues)

### ISSUE THREAD

**Issue by 3D-vice** [Roll20/roll20-character-sheets#11525]
ISSUE 1: Wrong calculation

When rolling a Driving Test on the Vehicle/Drone, the Piloting Skill (Groundcraft Skill in my example) is calculated incorrectly. It seems that the Reaction value is added to the Skill value, in addition to the actual Reaction value. Also, it seem that the Reaction value is then being subtracted again, yet incorrectly, as far as I can see. (?)

In my example (see screenshots):
Reaction Skill (10) 7+3
Groundcraft Skill (8) 7+1

Piloting Test with Vehicle:
Groundcraft (14) 7+3+7+1-7+3

Shouldn't the calculation for Groundcraft be 7+1 only?
Or 7+3+7+1-(7+3) if adding and substracting the Reaction is meant to be?

![Shadowrun 5th Edition (Advanced) BugReport DrivingTest](https://user-images.githubusercontent.com/82933178/221420686-a5050fa9-1c91-4731-b35f-130ed7073db1.jpg)

ISSUE 2: Wrong labeling

When rolling a Driving Test on the Vehicle/Drone, the Vehicle/Drone Type is displayed incorrectly. It always shows "Groundcraft", even when rolling for an Aircraft, Watercraft, Walker, or Aerospace. This only affects the labelling, since the values are taken from the correct appropriate Skill.

![Shadowrun 5th Edition (Advanced) BugReport VehicleType](https://user-images.githubusercontent.com/82933178/221420695-71dc723b-bb3b-40a2-932e-6c90c501aa16.jpg)

**Comment by Stexinator** [comment]
Fixed in https://github.com/Roll20/roll20-character-sheets/pull/11548

**Comment by Stexinator** [comment]
Fixed?

**Comment by 3D-vice** [comment]
Sorry for the delay of my answer. I just checked:

ISSUE 1: Wrong calculation > fixed!
ISSUE 2: Wrong labeling > not fixed *

* The sheet still displays "Groundcraft" when rolling a Driving Test via the "Maneuver" button, even if the Drone/Vehicle is set as Aircraft, Watercraft, Walker and Aerospace.

**Comment by Stexinator** [comment]
@3D-vice I cannot reproduce it. Did you changed it at least once? The fix changed the calculation so you have to change the value at least once. If you want to have Aerospace and you have it currently selected, select something different and then Aerospace again

**Comment by 3D-vice** [comment]
@Stexinator Good Morning! I just checked again and followed your recommendation and it worked propperly. Thanks for your feedback and for the fix.
