### ISSUE TITLE
Old Dragon 2e sheet no longer showing up on Roll20

### ISSUE THREAD

**Issue by jmonteiro** [Roll20/roll20-character-sheets#12862]
The [Old Dragon 2e](https://github.com/Roll20/roll20-character-sheets/blob/master/olddragon2e/sheet.json) sheet is no longer being shown on Roll20. It was in the list just a few weeks ago. I don't think anything changed in the files in order to prevent it from being shown. Any ideas what is causing the issue?

## Previously:

<img width="302" alt="image" src="https://github.com/Roll20/roll20-character-sheets/assets/3586/b5b48f2d-edfb-4b13-96b9-850265b8df94">

## Currently:

<img width="266" alt="image" src="https://github.com/Roll20/roll20-character-sheets/assets/3586/1fe4ce29-0e41-497a-9d23-99a8672ed452">

Notice that Old Dragon 2e is no longer shown.

**Comment by NorWhal** [comment]
Sorry for the confusion! This was unintentionally affected by an update to our sheet service and should now be resolved.

**Comment by Fahrenholz** [comment]
Hi @NorWhal , I still have the same problem with the [Private eye](https://github.com/Roll20/roll20-character-sheets/tree/master/Private%20Eye) sheet. Would you be able to look once more?

**Comment by NorWhal** [comment]
> Hi @NorWhal , I still have the same problem with the [Private eye](https://github.com/Roll20/roll20-character-sheets/tree/master/Private%20Eye) sheet. Would you be able to look once more?

@Fahrenholz Done!
