### ISSUE TITLE
[L5R 5th Edition Unofficial] Unarmed Skill Only Rolls 1 Air Ring

### ISSUE THREAD

**Issue by dyent** [Roll20/roll20-character-sheets#5612]
When rolling the Unarmed Skill it will only roll 1 Ring dice and reference the Air ring. This is regardless of which ring you select from the drop down menu and it will only roll 1 dice regardless of how many ranks in the air ring.
![image](https://user-images.githubusercontent.com/8639630/67649839-c5c1de80-f98e-11e9-8a5b-2e8c469b058a.png)

**Comment by Anduh** [comment]
Interesting. I looked at the button code and found no reason why this would be happening. Replicated behaviour.

**Comment by saethone** [comment]
Hey,

This was already corrected in a previous update. I think you posted this while the update was pending the push to roll20, it should be working normally as of a few weeks ago.

![image](https://user-images.githubusercontent.com/13894683/69351518-1270a080-0c41-11ea-8806-71c246eded7d.png)

**Comment by saethone** [comment]
Sorry I misread your problem, was thinking this was the NPC weapons table issue. This was a seperate problem - a missing field in a sheet worker. I'll submit a pull request this weekend with the update to correct it!

**Comment by Anduh** [comment]
> Sorry I misread your problem, was thinking this was the NPC weapons table issue. This was a seperate problem - a missing field in a sheet worker. I'll submit a pull request this weekend with the update to correct it!
That would make a lot of sense. When I tried this out 12 days ago the problem still existed as described. I only looked at the roll button,s and didn't find anything missing comparing to the other buttons, so for the problem existing in the sheet workers sounds likely.
Lesson learned, thanks!

**Comment by saethone** [comment]
Ok pull request submitted!

https://github.com/Roll20/roll20-character-sheets/pull/5700

It should be corrected the next time Roll20 updates their sheets.

**Comment by Anduh** [comment]
@dyent Did the update fix this issue?

**Comment by dyent** [comment]
Yes, does all seem to be working correctly now.
