### ISSUE TITLE
[Shadowrun5thEdition] Skills not translated after adding them to the character sheet

### ISSUE THREAD

**Issue by krakjen** [Roll20/roll20-character-sheets#5915]
When using a translated version of the character sheet, the Active Skills are only translated in the selection combo box.
Once selected and confirmed, they revert back to English.

I tested this with the French and Spanish character sheet and I don't think the issue is coming from the translation json.
Also, the issue was already there before the last fix to repeating skills, so it should not be related.

Attached capture of selecting the skills in French and how they all appears in English once selected.
![SR5_comp-bug1](https://user-images.githubusercontent.com/54226388/75826028-d653ec80-5da6-11ea-80ed-1d217c1edf69.png)
![SR5_comp-bug2](https://user-images.githubusercontent.com/54226388/75826035-da800a00-5da6-11ea-8115-70cc0d5599e8.png)

**Comment by clevett** [comment]
Fixed now?

**Comment by krakjen** [comment]
> Fixed now?

Doesn't look like it.
I just tested and they still appears in English.

**Comment by clevett** [comment]
I think I may know what's going on. I'll take a look this weekend.

**Comment by clevett** [comment]
Pull Request #5951 should fix this. However some translation keys may need adjusting. Let me know if any skills are not translating.

**Comment by krakjen** [comment]
> Pull Request #5951 should fix this. However some translation keys may need adjusting. Let me know if any skills are not translating.
It doesn't seem to be fixed unfortunately.
I was waiting for #5951 to be merged, but I just checked the character sheet and the skills are still untranslated.
Unless there is a delay between the commit and the sheet being updated in roll20 proper?

**Comment by clevett** [comment]
There is. Everything is merged Mondays and pulled on Tuesday. It should be updated now though.

**Comment by krakjen** [comment]
Alright, thanks for your hard work it's mostly fixed.

Two small issues though:
- For some reason Firearms and Close Combat Groups are no longer translated anywhere.
- Also the skills length are very short, making them hard to read (seems to be fixed now instead of dynamic).

![roll20_skills](https://user-images.githubusercontent.com/54226388/76902963-54cb8680-689d-11ea-8bbd-bc5017717e2c.png)

**Comment by krakjen** [comment]
Nevermind the first issue, I just checked the translation files and for some reason there was some regression. I'll correct it and add a pull request.
I don't know if the length issue is related.

**Comment by clevett** [comment]
I did that to the buttons. I'll adjust to show more text.

**Comment by krakjen** [comment]
They used to be dynamics but giving them the same length as the "Default a skill" one would be an elegant fix (and imho more useable).

**Comment by krakjen** [comment]
@clevett Have you had the time to look into fixing the skills box length?
Or should I open a different bug report for it?

**Comment by clevett** [comment]
Yep! I increased them a bit in the next pull request #6014 . Ultimately I'd like to provide a more dynamic option that gives them all the space if specializations are not added but for now its a compromise.

**Comment by krakjen** [comment]
Closing this thread since the issue is fixed :)
