### ISSUE TITLE
Weapon Entries Broken

### ISSUE THREAD

**Issue by Laoch97** [Roll20/roll20-character-sheets#6068]
In the Arms section, even with the proper skill selected for a weapon, it still only rolls the attribute without the skill rating. We've been manually adding the skill rating into the modifier section, which seems to work fine.

**Comment by vince-roll20** [comment]
Which sheet?

**Comment by Laoch97** [comment]
This is in reference to the Shadowrun 5e Roll20 Character Sheet

**Comment by Anduh** [comment]
@clevett this seems to be related you your sheet.

**Comment by clevett** [comment]
Also should have been fixed in #6014 . Let me know if its not working today.

**Comment by Laoch97** [comment]
It doesn't look like it works in my game right now. It still doesn't pull the skill rating.

**Comment by clevett** [comment]
Can you try changing the skill and changing it back?

**Comment by Laoch97** [comment]
It does look like it works now, thanks! Quick question, it looks like exploding sixes is on, is there a toggle for this to turn off?

**Comment by Laoch97** [comment]
Wait I figured it out, its just the edge toggle correct?

**Comment by clevett** [comment]
Yep. There is a bug that is toggle on exploding 6s when you enter an edge attribute. I've fixed the bug in #6085 . For now just use the edge toggle at the top of the page to toggle edge off and on then it will remove the ! as indicated by the toggle.
